# Generated by Django 5.2 on 2025-04-22 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Электроника', 'ELECTRONICS'), ('Одежда', 'CLOTHING'), ('Товары для дома', 'HOME'), ('Красота и здоровье', 'BEAUTY'), ('Книги', 'BOOKS'), ('Игрушки', 'TOYS'), ('Спорт и отдых', 'SPORTS')])),
                ('condition', models.CharField(choices=[('Новый', 'NEW'), ('Поношенный', 'WARNED'), ('Б/У', 'FORMERLY_USED')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('condition', models.CharField(choices=[('Ожидает', 'AWAITING'), ('Принят', 'ACCEPTED'), ('Отклонен', 'CANCELED')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad')),
            ],
            options={
                'unique_together': {('ad_sender', 'ad_receiver')},
            },
        ),
    ]
