# Generated by Django 5.2 on 2025-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='condition',
            field=models.CharField(choices=[('Ожидает', 'AWAITING'), ('Принят', 'ACCEPTED'), ('Отклонен', 'CANCELED')], default='Ожидает'),
        ),
    ]
