# Generated by Django 5.2 on 2025-04-22 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_exchangeproposal_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложения обмена'},
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Электроника', 'ELECTRONICS'), ('Одежда', 'CLOTHING'), ('Товары для дома', 'HOME'), ('Красота и здоровье', 'BEAUTY'), ('Книги', 'BOOKS'), ('Игрушки', 'TOYS'), ('Спорт и отдых', 'SPORTS')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('Новый', 'NEW'), ('Поношенный', 'WARNED'), ('Б/У', 'FORMERLY_USED')], max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad', verbose_name='Запрашиваемый товар'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad', verbose_name='Предлагаемый товар'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='condition',
            field=models.CharField(choices=[('Ожидает', 'AWAITING'), ('Принят', 'ACCEPTED'), ('Отклонен', 'CANCELED')], default='Ожидает', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
